config/routes.rb
Politics411::Application.routes.draw do  

  get "subcommittees/index"
  get "subcommittees/show"

  get "legislation/search"
  get "legislation/refresh"

  match "subcommittees/:id" => "subcommittees#show"

  get "contributor/show"

  get "committees/index"
  get "committees/manage"

  match "senators" => "people#senators"
  match "representatives" => "people#representatives"

  get "people/senators"
  get "people/representatives"
  get "people/refresh_officials"
  get "people/switch_to_representative_by_state"
  get "people/switch_to_representative_by_name"
  get "people/switch_to_representative_by_party"
  get "people/switch_to_senator_by_state"
  get "people/switch_to_senator_by_party"
  get "people/switch_to_senator_by_name"
  get "people/refresh_bubble_rect"
  get "people/person_not_found"
  post "people/search"

  get "api/autocomplete/autocomplete_person_name"
  get "api/autocomplete/autocomplete_person_name_to_slug"
  get "api/autocomplete/autocomplete_person_url"
  get "api/autocomplete/autocomplete_religion_name"
  get "api/autocomplete/autocomplete_university_name"
  get "api/autocomplete/autocomplete_organization_name"
  get "api/autocomplete/autocomplete_main_issues_name"
  get "api/autocomplete/autocomplete_issues_name"

  get "api/people/index"

  get "login" => "sessions#new", :as => "login"
  get "logout" => "sessions#destroy", :as => "logout"
  get "signup" => "users#new", :as => "signup"

  resources :people do
    member do 
      get 'videos'
      get 'articles'
    end
  end
  resources :main_issues
  resources :issues
  resources :committees
  resources :subcommittees
  resources :legislation
  resources :users
  resources :password_resets
  resources :sessions
  resources :contributors_interest_group_sectors
  resources :contributors_interest_groups
  resources :contributors_pacs
  resources :political_offices
  resources :earmarks
  resources :sponsored_legislations  
  resources :campaign_platforms
  resources :supporters
  resources :contributors
  resources :articles 
  resources :attachments
  resources :personal_assets
  resources :transactions
  resources :litigations
  resources :accusations
  resources :endorsements
  resources :professional_experiences
  resources :business_associates
  resources :organizations
  resources :flip_flops
  resources :videos
  resources :family_members
  resources :religions
  resources :universities 
  resources :degrees

  root :to => "people#representatives"

  match ':controller(/:action(/:id(.:format)))'
end

app/controllers/api/people_controller.rb
class Api::PeopleController < ApplicationController
  def index
    @people = Person.all
  end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController

  layout 'public'

  load_and_authorize_resource
  skip_authorize_resource :only => [
    :all                               , :show                             ,
    :representatives                   , :senators                         ,
    :indiv_contributors                , :pac_contributors                 ,
    :refresh_officials                 , :switch_to_senator_by_party       ,
    :switch_to_representative_by_state , :switch_to_representative_by_name ,
    :switch_to_representative_by_party , :switch_to_senator_by_state       ,
    :switch_to_senator_by_name         , :refresh_bubble_rect              ,
    :videos                            , :articles                         ,
    :search
  ]

  def index
    render 'all'
  end

  def all
    @people = Person.order("people.id ASC")

    respond_to do |format|
      format.html # all.html.erb
      format.json { render :json => @people}
      format.xml { render xml: @people }
    end
  end

  def show
    if params[:name]
      @person = Person.where(:name => params[:name])
      endpoint = "http://ap411.pagodabox.com/official/"
      url = endpoint + @person.slug + "/?output=json"
      @articles = fetch_json(url)
    else
      @person = Person.find(params[:id])
      endpoint = "http://ap411.pagodabox.com/official/"
      url = endpoint + @person.slug + "/?output=json"
      @articles = fetch_json(url)
    end

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @person }
    end
  end

  def search
    @person = Person.where(:name => params[:name]).first
    endpoint = "http://ap411.pagodabox.com/official/"
    url = endpoint + @person.slug + "/?output=json"
    @articles = fetch_json(url)

    if @person
      redirect_to :action => 'show', :id => @person.slug
    else
      render :action => 'person_not_found', :locals => {:name => params[:name]}
    end
  end

  def person_not_found
  end

  def videos
    @person = Person.find(params[:id])
  end

  def articles
    @person = Person.find(params[:id])
  end

  def senators
    @people = Person.where("chamber = 'S'").order("people.last_name ASC")
  end

  def representatives
    @people = []
  end

  def switch_to_representative_by_state
    respond_to do |format|
      format.js { render :layout => false }
    end
  end

  def switch_to_representative_by_name
    respond_to do |format|
      format.js { render :layout => false }
    end 
  end

  def switch_to_representative_by_party
    respond_to do |format|
      format.js { render :layout => false }
    end 
  end

  def switch_to_senator_by_state
    respond_to do |format|
      format.js { render :layout => false }
    end
  end

  def switch_to_senator_by_name
    respond_to do |format|
      format.js { render :layout => false }
    end
  end

  def switch_to_senator_by_state
    respond_to do |format|
      format.js { render :layout => false }
    end
  end

  def get_professional_experience_text
    respond_to do |format|
      format.js { render :layout => false }
    end 
  end

  def refresh_bubble_rect
    @person = Person.find(params[:pid])

    respond_to do |format|
      format.js
    end
  end

  def refresh_officials
    if params.has_key?(:state_represented) && params.has_key?(:chamber)
      @people = Person.where(:state_represented => params[:state_represented], :chamber => params[:chamber]).includes(:addresses)
    elsif params.has_key?(:name) && params.has_key?(:chamber)
      name_range  = params[:name].split('-')
      @people = Person.where("chamber = '#{params[:chamber]}' AND last_name BETWEEN '#{name_range[0]}' AND '#{name_range[1]}'").includes(:addresses)
    elsif params.has_key?(:chamber) && params.has_key?(:party)
      @people = Person.where(:chamber => params[:chamber], :current_party => params[:party]).includes(:addresses)
    elsif params.has_key?(:state)
      @people = Person.where(:state_represented => params[:state]).includes(:addresses)
    elsif params.has_key?(:party)
      @people = Person.where(:current_party => params[:party]).includes(:addresses)
    elsif params.has_key?(:chamber)
      @people = Person.where(:chamber => params[:chamber]).includes(:addresses)
    end

    respond_to do |format|
      format.js { render :layout => false }
    end
  end

  def pac_contributors
    @person = Person.find(params[:id])
    @pac_contributors = TransparencyData::Client.contributions(
      :recipient_ft => "#{@person.remove_name_numericality}", 
      :cycle => 2011, 
      :amount => {:gte => 2300},
      :contributor_type => "C")
  end

  def indiv_contributors
    @person = Person.find(params[:id])
    @individual_contributors = TransparencyData::Client.contributions(
      :recipient_ft => "#{@person.remove_name_numericality}", 
      :cycle => 2011, 
      :amount => {:gte => 1000},
      :contributor_type => "I")
  end

  def new
    @person = Person.new
    @religions = Religion.order('id ASC')

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @person }
    end
  end

  def edit
    @person = Person.find(params[:id])
  end

  def create
    @person = Person.new(params[:person])

    respond_to do |format|
      if @person.save
        format.html { 
          flash[:notice] = 'Person added successfully.'
          redirect_to(:action => 'edit', :id => @person.id)
        }
        format.json { render json: @person, status: :created, location: @person }
      else
        format.html { render action: "new" }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @person = Person.find(params[:id])

    respond_to do |format|
      if @person.update_attributes(params[:person])
        format.html { 
          flash[:notice] = 'Person has been successfully updated.'
          render 'edit'  }
          format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @person = Person.find(params[:id])
    @person.destroy

    respond_to do |format|
      format.html { 
        flash[:notice] = "Person removed."
        redirect_to :back
      }
      format.json { head :ok }
    end
  end


  private

  def fetch_json(url)
    require 'json'
    require 'net/http'

    begin
      resp = Net::HTTP.get_response(URI.parse(url))
      data = resp.body
      JSON.parse(data)
    rescue Exception => e
    end
  end

end

app/helpers/api/people_helper.rb
module Api::PeopleHelper
end

app/helpers/people_helper.rb
module PeopleHelper
  def no_separator
    options={:words_connector => '', :two_words_connector => '', :last_word_connector => ''}
  end

  def party_breakdown
    if @id.nil?
      "N/A"
    else
      @stats = TransparencyData::Client.individual_party_breakdown(@id)
      @dem_count = @stats.dem_count.to_f
      @rep_count = @stats.rep_count.to_f
      @dem_percent = (@dem_count / (@dem_count + @rep_count)) * 100
      @rep_percent = (@rep_count / (@dem_count + @rep_count)) * 100
      if @dem_percent > @rep_percent
        "<p>#{sprintf("%0.02f", @dem_percent)}% Democratic (#{@dem_count.to_i})</p>
         <p>#{sprintf("%0.02f", @rep_percent)}% Republican (#{@rep_count.to_i})</p>".html_safe
      elsif @dem_percent == @rep_percent
        "<p>#{sprintf("%0.02f", @dem_percent)}% Democratic (#{@dem_count.to_i})</p>
         <p>#{sprintf("%0.02f", @rep_percent)}% Republican (#{@rep_count.to_i})</p>".html_safe
      else
        "<p>#{sprintf("%0.02f", @rep_percent)}% Republican (#{@rep_count.to_i})</p>
         <p>#{sprintf("%0.02f", @dem_percent)}% Democratic (#{@dem_count.to_i})</p>".html_safe
      end
    end
  end

  def state_federal_breakdown
    if @id.nil?
      "N/A"
    else
      @stats = TransparencyData::Client.org_level_breakdown(@id)
      @fed_amount = @stats.federal_amount
      @state_amount = @stats.state_amount
      @fed_count = @stats.federal_count.to_f
      @state_count = @stats.state_count.to_f
      @fed_percent = (@fed_count / (@fed_count + @state_count)) * 100
      @state_percent = (@state_count / (@fed_count + @state_count)) * 100
      "<p>Federal Contributions: #{sprintf("%0.02f", @fed_percent)}% (#{number_to_currency(@fed_amount)})</p>
       <p>State Contributions: #{sprintf("%0.02f", @state_percent)}% (#{number_to_currency(@state_amount)})</p>".html_safe
    end
  end

  def contributions_by_sector_math
    @i = 0
    @sectors.each do |s|
      @i = @i + s.amount.to_i
    end    
  end

  def get_tweet_ids
    @tweet_ids = []
    @tweet_text = []
    @tweets = @recent_tweets.each do |t|
      @tweet_ids << t.id
    end
  end

  def bubble_safe(str, opts={})
    opts[:width] ||= 80
    zero_width_space = "&#8203;"
      regex = /.{1,#{opts[:width]}}/
      (str.length < opts[:width]) ? text :
      str.scan(regex).join(zero_width_space)
  end

  def js_safe(html)
    html.html_safe.gsub(/\r/, "\\r").gsub(/\n/, "\\n") 
  end

  def print_contact_info
    contact_info = @person.contact_phone
  end

  def fetch_json(url)
    require 'json'
    require 'net/http'

    begin
      resp = Net::HTTP.get_response(URI.parse(url))
      data = resp.body
      json = JSON.parse(data)

      return json
    rescue Exception => e
    end
  end

  def fetch_pfd_profile(person)
    require 'json'
    require 'net/http'

    apikey = "3c994a55a6b79f30f22b6b3942941f62"
    endpoint = "http://www.opensecrets.org/api/?method=memPFDprofile"

    cid = person.crp_id

    if cid.nil?
      cid = get_crp_id(person.last_name)
      if cid.empty?
        return []
      else
        person.crp_id = cid
        person.save
      end
      url = endpoint + "&year=2009&cid=" + cid + "&output=json&apikey=" + apikey
      json = fetch_json(url)

      return json
    else
      url = endpoint + "&year=2009&cid=" + cid + "&output=json&apikey=" + apikey
      json = fetch_json(url)

      return json
    end
  end

  def fetch_net_worth(person)
    json = fetch_pfd_profile(person)
    if json.empty?
      return []
    else
      json_attributes = json['response']['member_profile']['@attributes']
      @net_worth_minimum = json_attributes['net_low'].to_i
      @net_worth_maximum = json_attributes['net_high'].to_i
      @net_worth_average = (@net_worth_maximum + @net_worth_minimum) / 2
    end

    return @net_worth_minimum, @net_worth_maximum, @net_worth_average
  end

  def fetch_votes(person)
    nyt_apikey = "b16efb69e13af05498fe536551a7bc67:15:65673083"
    nyt_endpoint = "http://api.nytimes.com/svc/politics/v3/us/legislative/congress/members/"
    if person.bioguide_id.nil?
      @bioguide_id = get_bioguide_id(person.last_name)
      if @bioguide_id.empty?
        return []
      else
        # save the bioguide id
        person.bioguide_id = @bioguide_id
        person.save

        nyt_url = nyt_endpoint + @bioguide_id + "/votes.json?api-key=" + nyt_apikey
        json = fetch_json(nyt_url)

        return json
      end
    else
      @bioguide_id = person.bioguide_id
      nyt_url = nyt_endpoint + @bioguide_id + "/votes.json?api-key=" + nyt_apikey
      json = fetch_json(nyt_url)

      return json
    end
  end

  def get_bioguide_id(name)
    govtrack_endpoint = "http://www.govtrack.us/api/v1/person/?lastname=" + name
    govtrack_json = fetch_json(govtrack_endpoint)
    govtrack_count = govtrack_json['meta']['total_count']
    if govtrack_count > 0 && govtrack_count < 2
      bioguide_id = govtrack_json['objects'][0]['bioguideid']
      return bioguide_id
    else
      return []
    end
  end

  def get_crp_id(name)
    # get the crp_id using firstname, lastname, nameod
    govtrack_endpoint = "http://www.govtrack.us/api/v1/person/?lastname=" + name
    govtrack_json = fetch_json(govtrack_endpoint)
    govtrack_count = govtrack_json['meta']['total_count']

    if govtrack_count > 0 && govtrack_count < 2
      crp_id = govtrack_json['objects'][0]['osid']
      return crp_id
    else
      return []
    end
  end

  def parse_google_rss_feed(full_name, options={})
    options[:num] ||= 10
    full_name = full_name.gsub(/ /, "%20")
    endpoint = "http://news.google.com/news?q=" 
    url = endpoint + full_name + "&output=rss&num=" + options[:num].to_s
    feed = Feedzirra::Feed.fetch_and_parse(url)
    articles = feed.entries

    return articles
  end

  def parse_google_summary(summary)
    doc = Nokogiri::HTML(summary)
    summary = doc.xpath('//div/font[2]').inner_text

    return summary
  end

  def parse_book(b)
    book = b.get_hash
    attributes = "<Book>" + book["ItemAttributes"] + "</Book>"
    book_attributes = Nokogiri::XML(attributes)
    @url = book["DetailPageURL"]
    @title = book_attributes.xpath('//Title').inner_text
    @author = book_attributes.xpath('//Author').inner_text
    unless b.get_hash('SmallImage').nil?
      @image = b.get_hash('SmallImage')["URL"]
    end

    return @url, @title, @author, @image
  end

  def get_demographics(person)
    begin
      @entity = TransparencyData::Client.entities(:search => "#{person.remove_name_numericality}")
      if @entity.empty?
        @entity = TransparencyData::Client.id_lookup(:namespace => "urn:crp:recipient", :id => person.crp_id)
      end

      if @entity.first
        @id = @entity.first.id
        @sectors = TransparencyData::Client.top_sectors(@id)
      else
        @sectors = []
      end
    rescue Exception => e
      @success = false
    end

    return @sectors, @id, @success, @entity
  end

  def load_demographic_pie_percentages(sectors)
    contributions_by_sector_math
    @demographic_pie_percentages = [] 
    @legend = []
    @sectors.collect do |s|
      percentage = sprintf("%0.02f", ((s.amount.to_f / @i.to_f)) * 100).to_f
      percentage_as_percent = number_to_percentage(percentage, :precision => 2)
      legend = percentage_as_percent + " " + s.name + " - (#{number_to_currency(s.amount)})"
      @demographic_pie_percentages << percentage
      @legend << legend
    end

    return @demographic_pie_percentages, @legend
  end

end

app/views/people/_accusations_text.html.erb
<% p = Person.find(params[:pid]) %>
<% accusations = p.accusations %>

<div class="scrollable-layover">
  <h1 class="popup-title">Accusations</h1>
  <% if accusations.count > 0 %>
    <table class="table-striped">
      <thead>
        <th>Date</th>
        <th>Accusation</th>
        <th>Outcome</th>
      </thead>
      <tbody>
        <% accusations.each do |a| %>
        <tr>
          <td><%= a.date.year %></td>
          <td><%= a.accusation %></td>
          <td><%= a.outcome %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
  <% else %>
    <p>Research is currently in progress.</p>
  <% end %>
</div>

app/views/people/_browse_people.html.erb
<div class="representatives-col1 three columns">
  <h1>Everyone</h1>
  <p>Know of an individual serving in Federal, State, or Local politics? Search for their name here. Make sure to type their name as accurately as possible.</p>
  <%= form_tag people_search_path, :method => :post do %>
    <%= text_field_tag :name, params[:name], :id => 'name', :name => 'name', :class => 'person-search', data: {people_source: api_autocomplete_autocomplete_person_name_path} %>
    <%= submit_tag 'Go', :class => 'submit-search' %>
  <% end %>
</div>
<div id="menu-item-officials-subnav-col2" class="representatives-col2 three columns one-of-five">
  <ul>
    <li class="list-header">Presidential Candidates</li>
    <li><%= link_to "Mitt Romney", :action => 'show', :id => '4489-Governor Mitt-Romney' %></li>
    <li><%= link_to "Barack Obama", :action => 'show', :id => '4488-President-Barack-Obama' %></li>
  </ul>
</div>
<div id="menu-item-officials-subnav-col3" class="representatives-col3 three columns one-of-five">
  <ul>
    <li class="list-header">Congress</li>
    <li><%= link_to "House of Representatives", people_representatives_path %></li>
    <li><%= link_to "Senate", people_senators_path %></li>
    <li><%= link_to "Joint Committees" %></li>
  </ul>
</div>
<div id="menu-item-officials-subnav-col4" class="representatives-col4 three columns one-of-five">
  <ul>
    <li class="list-header">Supreme Court</li>
    <li>John Roberts</li>
    <li>Antonin Scalia</li>
    <li>Anthony M. Kennedy</li>
    <li>Clarence Thomas</li>
    <li>Ruth Bader Ginsburg</li>
    <li>Stephen G. Breyer</li>
    <li>Samuel Anthony Alito</li>
    <li>Sonia Sotomayor</li>
    <li>Elena Kagan</li>
  </ul>
</div>
<div id="menu-item-officials-subnav-col5" class="representatives-col5 three columns one-of-five">
  <ul>
    <li class="list-header">Executive Branch</li>
    <li>Barack Obama</li>
    <li>Joe Biden</li>
    <li>The Cabinet</li>
  </ul>
</div>

app/views/people/_controversy_text.html.erb
<h1>THIS SHOULD NOT BE CLICKABLE</h1>

app/views/people/_earmarks_text.html.erb
<% p = Person.find(params[:pid]) %>
<% earmarks = p.earmarks %>

<h1 class="popup-title">Earmarks</h1>
<% if earmarks.count > 0 %>
  <div id="data-table-wrapper" style="width: 920px;">
    <p class="attribution">SOURCE: <a href="http://www.opensecrets.org">OpenSecrets.org</a></p>
    <table id="data-table">
      <thead>
        <tr>
          <th>Year</th>
          <th>Description</th>
          <th>Bill</th>
          <th>Amount</th>
        </tr>
      </thead>
      <tbody style="300px;">
        <% earmarks.each do |e| %>
        <tr>
          <td><%= e.fiscal_year %></td>
          <td><%= truncate(e.description, :length => 70) %></td>
          <td><%= truncate(e.bill, :length => 50) %></td>
          <td><%= number_to_currency(e.final_amount, :precision => 0) %></td>
          <% end %>
        </tr>
      </tbody>
    </table>
  </div>
<% else %>
  <p>No earmarks on record for <%= p.full_name %>.</p>
<% end %>

app/views/people/_endorsement_fields.html.erb
<tr class="fields actions">
	<%= f.hidden_field :person_id, :value => @person.id %>
	
 	<td><%= f.text_field :organization_name, :class => 'organization-list', data: {organizations_source: api_autocomplete_autocomplete_organization_name_path} %></td>
	<td><%= f.date_select :year, {:start_year => 1951, :discard_day => true, :discard_month => true}, {:class => 'span2'} %></td>
	<td><%= link_to_remove_fields "remove", f %></td>
</tr>

app/views/people/_family_network_text.html.erb
<% p = Person.find(params[:pid]) %>
<% family_members = p.family_members %>

<div class="scrollable-layover">
  <h1 class="popup-title">Family Network</h1>
  <% if family_members.count > 0 %>
  <table class="table-striped" style="width: 900px;">
    <thead>
      <tr>
        <th>Name</th>
        <th>Relationship</th>
        <th>Notes</th>
      </tr>
    </thead>
    <tbody>
      <% family_members.each do |f| %>
      <tr>
        <td><%= f.family_member %></td>
        <td><%= f.relationship %></td>
        <td><%= f.notes %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
  <% else %>
  <p>Research is in progress.</p>
  <% end %>
</div>

app/views/people/_flip_flop_fields.html.erb
<tr class="fields actions">
	<%= f.hidden_field :person_id, :value => @person.id %>

    <td><%= f.date_select(:year, :start_year => 1951, :discard_day => true, :discard_month => true) %></td>
    <td><%= f.text_field :issue %></td>
    <td><%= f.text_field :flipflop %></td>
		<td><%= link_to_remove_fields "remove", f %></td>
</tr>

app/views/people/_media.html.erb
<div id="media-center-videos" class="seven columns">
  <% if @person.youtube_id.blank? %>
    <% @personal_videos = $youtube.videos_by(:query => "#{@person.full_name}", :page => 1, :per_page => 15) %>
    <% @personal_videos.videos.each do |v| %>
      <% title = v.title %>
      <% thumbnail = v.thumbnails.first.url %>
      <% video_url = v.media_content[0].url %>
      <div class="youtube-video">
        <%= link_to image_tag(thumbnail), video_url, :class => 'video-thumb' %>
        <div class="video-thumb-layover" style="display:none">
          <p><%= link_to truncate(title, length: 45), video_url %></p>
        </div>
      </div>
    <% end %>
    <br>
    <%= link_to "More Videos >>", videos_person_path(@person), :id => 'more-videos-link' %>
    <p style="font-size:11px;">* These videos are <b>not</b> from the official youtube account of <%= @person.first_last_name %>.</p>
  <% else %>
    <% begin %>
      <% @personal_videos = $youtube.videos_by(:user => "#{@person.youtube_id}", :page => 1, :per_page => 15) %>
    <% rescue %>
    <% else %>
      <% @personal_videos.videos.each do |v| %>
        <% title = v.title %>
        <% thumbnail = v.thumbnails.first.url %>
        <% video_url = v.media_content[0].url %>
        <div class="youtube-video">
          <%= link_to image_tag(thumbnail), video_url, :class => 'video-thumb' %>
          <div class="video-thumb-layover" style="display:none">
           <p><%= link_to truncate(title, length: 45), video_url %></p>
          </div>
        </div>
      <% end %>
      <%= link_to "More Videos >>", videos_person_path(@person), :id => 'more-videos-link' %>
    <% end %>
  <% end %>
</div>

app/views/people/_organization_person_fields.html.erb
<tr class="fields">
  <%= f.hidden_field :person_id, :value => @person.id %>
  <td>
    <%= f.select(:organization_id, Organization.all.collect {|o| [o.name, o.id]}) %>
    <%= link_to "Add Organization", new_organization_path %>
  </td>
  <td><%= f.text_field :position %></td>
  <td><%= link_to_remove_fields "remove", f %></td>
</tr>

app/views/people/_personal_asset_fields.html.erb
<tr class="fields actions">
  <%= f.hidden_field :person_id, :value => @person.id %>

  <td><%= f.text_field :organization_name, :class => 'organization-list', data: {organizations_source: api_autocomplete_autocomplete_organization_name_path} %></td>
  <td><%= f.text_field :value, :class => 'span2' %></td>
  <td><%= f.text_field :value_min, :class => 'span2' %></td>
  <td><%= f.text_field :value_max, :class => 'span2' %></td>
  <td><%= link_to_remove_fields "remove", f %></td>
</tr>

app/views/people/representatives.html.erb
<%= stylesheet_link_tag 'representatives' %>

<div class="page-header">
  <%= render 'layouts/messages' %>
</div>

<div class="content-wrap sixteen columns">
  <ul class="tabs">
    <li><a class="active" href="#house">House</a></li>
    <li><a href="#senate">Senate</a></li>
    <li><a href="#people">Everyone</a></li>
  </ul>
  <ul class="tabs-content">
    <li class="active" id="house">
      <div class="selector-container">
        <div class="representatives-col1 three columns">
          <h1>House of Representatives</h1>
          <ul>
            <li><%= link_to "Browse by State", {:action => 'switch_to_representative_by_state'}, :remote => true %></li>
            <li><%= link_to "Browse by Name", {:action => 'switch_to_representative_by_name'}, :remote => true %></li>
            <li><%= link_to "Browse by Party", {:action => 'switch_to_representative_by_party'}, :remote => true %></li>
          </ul>
          <%= form_tag people_search_path, :method => :post do %>
          <div class="row">
            <%= text_field_tag :name, params[:name], :id => 'name', :name => 'name', :class => 'person-search', data: {people_source: api_autocomplete_autocomplete_person_name_path} %>
            <%= submit_tag 'Go', :class => 'submit-search' %>
          </div>
          <% end %>
        </div>
        <div class="navigation-container">
          <%= render :partial => 'browse_by_state', :locals => {:chamber => 'H'} %>
        </div>
      </div>
    </li>
    <li id="senate">
      <div class="selector-container">
        <div class="representatives-col1 three columns">
          <h1>Senate</h1>
          <ul>
            <li><%= link_to "Browse by State", {:action => 'switch_to_senator_by_state'}, :remote => true %></li>
            <li><%= link_to "Browse by Name", {:action => 'switch_to_senator_by_name'}, :remote => true %></li>
            <li><%= link_to "Browse by Party", {:action => 'switch_to_senator_by_party'}, :remote => true %></li>
          </ul>
          <%= form_tag people_search_path, :method => :post do %>
            <%= text_field_tag :name, params[:name], :id => 'name', :name => 'name', :class => 'person-search', data: {people_source: api_autocomplete_autocomplete_person_name_path} %>
            <%= submit_tag 'Go', :class => 'submit-search' %>
          <% end %>
        </div>
        <div class="navigation-container">
          <%= render :partial => 'browse_by_state', :locals => {:chamber => 'S'} %>
        </div>
      </div>
    </li>
    <li id="people">
      <div class="selector-container">
        <%= render :partial => 'browse_people' %>
      </div>
    </li>
  </ul>
</div>

<% if current_user %>
  <div id="person-container" class="fifteen columns box_a">
<% else %>
  <div id="person-container" class="fifteen columns box_a" style="margin-top: 10px;">
<% end %>
    <%= render :partial => 'person_partial', :locals => {:people => @people} %>
</div>