config/routes.rb
Politics411::Application.routes.draw do  

  get "subcommittees/index"
  get "subcommittees/show"

  get "legislation/search"
  get "legislation/refresh"

  match "subcommittees/:id" => "subcommittees#show"

  get "contributor/show"

  get "committees/index"
  get "committees/manage"

  match "senators" => "people#senators"
  match "representatives" => "people#representatives"

  get "people/senators"
  get "people/representatives"
  get "people/refresh_officials"
  get "people/switch_to_representative_by_state"
  get "people/switch_to_representative_by_name"
  get "people/switch_to_representative_by_party"
  get "people/switch_to_senator_by_state"
  get "people/switch_to_senator_by_party"
  get "people/switch_to_senator_by_name"
  get "people/refresh_bubble_rect"
  get "people/person_not_found"
  post "people/search"

  get "api/autocomplete/autocomplete_person_name"
  get "api/autocomplete/autocomplete_person_name_to_slug"
  get "api/autocomplete/autocomplete_person_url"
  get "api/autocomplete/autocomplete_religion_name"
  get "api/autocomplete/autocomplete_university_name"
  get "api/autocomplete/autocomplete_organization_name"
  get "api/autocomplete/autocomplete_main_issues_name"
  get "api/autocomplete/autocomplete_issues_name"

  get "api/people/index"

  get "login" => "sessions#new", :as => "login"
  get "logout" => "sessions#destroy", :as => "logout"
  get "signup" => "users#new", :as => "signup"

  resources :people do
    member do 
      get 'videos'
      get 'articles'
    end
  end
  resources :main_issues
  resources :issues
  resources :committees
  resources :subcommittees
  resources :legislation
  resources :users
  resources :password_resets
  resources :sessions
  resources :contributors_interest_group_sectors
  resources :contributors_interest_groups
  resources :contributors_pacs
  resources :political_offices
  resources :earmarks
  resources :sponsored_legislations  
  resources :campaign_platforms
  resources :supporters
  resources :contributors
  resources :articles 
  resources :attachments
  resources :personal_assets
  resources :transactions
  resources :litigations
  resources :accusations
  resources :endorsements
  resources :professional_experiences
  resources :business_associates
  resources :organizations
  resources :flip_flops
  resources :videos
  resources :family_members
  resources :religions
  resources :universities 
  resources :degrees

  root :to => "people#representatives"

  match ':controller(/:action(/:id(.:format)))'
end

app/models/issue.rb
class Issue < ActiveRecord::Base

  attr_accessible :name
  
  has_many :issue_main_issues
  has_many :main_issues, :through => :issue_main_issues  

  def to_param
    "#{id} #{name.capitalize}".parameterize
  end
end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController

  layout 'public'

  load_and_authorize_resource
  skip_authorize_resource :only => [:index, :show]

  def index
    @issues = Issue.order('id ASC')
  end

  def show
    @issue = Issue.find(params[:id])
    @legislative_issue = Issue.where("name like ?", "#{@issue.name}").first.id
    @bills = LegislationIssue.where("issue_id = #{@legislative_issue}")
  end

  def edit
    @issue = Issue.find(params[:id])
  end

  def update
    @issue = Issue.find(params[:id])

    respond_to do |format|
      if @issue.update_attributes(params[:issue])
        format.html {
          flash[:notice] = "#{@issue.name} has been successfully updated."
          redirect_to(:action => 'index')
        }
      else
        format.html { render action: 'edit' }
      end 
    end
  end
end

app/helpers/issues_helper.rb
module IssuesHelper
  def split_main_issues
    @main_issues = MainIssue.order('name ASC')

    count = MainIssue.count
    split_count = count / 3

    x1 = 0
    y1 = split_count - 1
    x2 = split_count
    y2 = (split_count * 2) - 1
    x3 = split_count * 2
    y3 = (split_count * 3)

    @row1 = @main_issues[x1..y1]
    @row2 = @main_issues[x2..y2]
    @row3 = @main_issues[x3..y3]
  end
end

app/views/issues/_form.html.erb
<%= form_for(@issue, :html => { :class => "form-stacked" }) do |f| %>
  <%= error_messages_for(@issue) %>

  <%= f.label "Belongs to Main Issues:" %>

  <div class="issues">
    <% split_main_issues %>
    <%= hidden_field_tag "issue[main_issue_ids][]", nil %>
    <div class="issues_row">
      <% @row1.each do |main_issue| %>
        <%= check_box_tag "issue[main_issue_ids][]", main_issue.id, @issue.main_issue_ids.include?(main_issue.id)  %>
        <%= main_issue.name %><br />
      <% end %>
    </div>
    <div class="issues_row">
      <% @row2.each do |main_issue| %>
        <%= check_box_tag "issue[main_issue_ids][]", main_issue.id, @issue.main_issue_ids.include?(main_issue.id)  %>
        <%= main_issue.name %><br />
      <% end %>
    </div>
    <div class="issues_row">
      <% @row3.each do |main_issue| %>
        <%= check_box_tag "issue[main_issue_ids][]", main_issue.id, @issue.main_issue_ids.include?(main_issue.id)  %>
        <%= main_issue.name %><br />
      <% end %>
    </div>
  </div>

  <%= f.submit :class => 'btn success' %>
<% end %>

app/views/issues/edit.html.erb
<div class="container">
  <h1>Editing <%= @issue.name %></h1>

  <%= render 'form' %>

  <%= link_to 'Back', issues_path %>
</div>

app/views/issues/index.html.erb
<div class="sixteen columns">
  <h1 class="page-title">Issues</h1>
  <table class="table-striped">
    <thead>
      <tr>
        <th class="span10">Name</th>
        <th>Assigned To</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @issues.each do |issue| %>
      <tr class="<%= cycle('even', 'odd') %>">
        <td><%= link_to "#{issue.name}", issue %></td>
        <td><%= issue.main_issues.collect { |mi| mi.name }.to_sentence %></td>
        <% if can? :edit, Issue %>
        <td><%= link_to "Edit", edit_issue_path(issue) %></td>
        <% else %>
        <td></td>
        <% end %>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/issues/show.html.erb
<div class="sixteen columns">
  <h1 class="page-title"><%= @issue.name %></h1>
  <table class="table-striped">
    <thead>
      <tr>
        <th>Bill Number</th>
        <th>Description</th>
      </tr>
    </thead>
    <tbody>
      <% @bills.each do |bill| %>
      <% legislation = Legislation.find(bill.legislation.id) %>
      <% bill_number = "#{legislation.bill_type.upcase} #{legislation.bill_number}" %>
      <tr class="<%= cycle("even", "odd") %>">
        <td><%= link_to bill_number, legislation %></td>
        <td><%= link_to truncate(legislation.bill_title, :length => 130), legislation %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>