config/routes.rb
Politics411::Application.routes.draw do  

  get "subcommittees/index"
  get "subcommittees/show"

  get "legislation/search"
  get "legislation/refresh"

  match "subcommittees/:id" => "subcommittees#show"

  get "contributor/show"

  get "committees/index"
  get "committees/manage"

  match "senators" => "people#senators"
  match "representatives" => "people#representatives"

  get "people/senators"
  get "people/representatives"
  get "people/refresh_officials"
  get "people/switch_to_representative_by_state"
  get "people/switch_to_representative_by_name"
  get "people/switch_to_representative_by_party"
  get "people/switch_to_senator_by_state"
  get "people/switch_to_senator_by_party"
  get "people/switch_to_senator_by_name"
  get "people/refresh_bubble_rect"
  get "people/person_not_found"
  post "people/search"

  get "api/autocomplete/autocomplete_person_name"
  get "api/autocomplete/autocomplete_person_name_to_slug"
  get "api/autocomplete/autocomplete_person_url"
  get "api/autocomplete/autocomplete_religion_name"
  get "api/autocomplete/autocomplete_university_name"
  get "api/autocomplete/autocomplete_organization_name"
  get "api/autocomplete/autocomplete_main_issues_name"
  get "api/autocomplete/autocomplete_issues_name"

  get "api/people/index"

  get "login" => "sessions#new", :as => "login"
  get "logout" => "sessions#destroy", :as => "logout"
  get "signup" => "users#new", :as => "signup"

  resources :people do
    member do 
      get 'videos'
      get 'articles'
    end
  end
  resources :main_issues
  resources :issues
  resources :committees
  resources :subcommittees
  resources :legislation
  resources :users
  resources :password_resets
  resources :sessions
  resources :contributors_interest_group_sectors
  resources :contributors_interest_groups
  resources :contributors_pacs
  resources :political_offices
  resources :earmarks
  resources :sponsored_legislations  
  resources :campaign_platforms
  resources :supporters
  resources :contributors
  resources :articles 
  resources :attachments
  resources :personal_assets
  resources :transactions
  resources :litigations
  resources :accusations
  resources :endorsements
  resources :professional_experiences
  resources :business_associates
  resources :organizations
  resources :flip_flops
  resources :videos
  resources :family_members
  resources :religions
  resources :universities 
  resources :degrees

  root :to => "people#representatives"

  match ':controller(/:action(/:id(.:format)))'
end

app/models/legislation.rb
class Legislation < ActiveRecord::Base

  attr_accessible :rtc_id, :bill_type, :bill_number, :session, :introduced_year, :introduced_date, :chamber, :short_title, :bill_title, :popular_title, :summary, :bill_sponsor, :bill_sponsor_id, :bill_pdf, :latest_major_action, :latest_major_action_date

  before_save :set_introduced_year

  has_many :actions
  has_many :passage_votes
  has_many :person_votes

  has_many :committee_legislations
  has_many :committees, :through => :committee_legislations

  has_many :legislation_cosponsors
  has_many :people, :through  => :legislation_cosponsors

  has_many :legislation_issues
  has_many :issues, :through => :legislation_issues

  SESSIONS = [112, 111]
  YEARS = [2012, 2011, 2010, 2009, 2008]

  def set_introduced_year
    unless self.introduced_year.nil?
      self.introduced_year = self.introduced_date.split('-').shift
    end
  end

end

app/controllers/legislation_controller.rb
class LegislationController < ApplicationController

  layout 'public'

  def index
    @legislation = Legislation.order('introduced_date DESC').page(params[:page]).per(25).includes(:passage_votes)
  end

  def refresh
    if params[:legislations][:introduced_year]
      year = params[:legislations][:introduced_year]
      @legislation = Legislation.where("introduced_year = ?", "#{year}")
        .order('introduced_date DESC')
        .page(params[:page]).per(25)
    elsif params[:legislations][:session]
      congress_year = params[:legislations][:session]
      @legislation = Legislation.where(:session => congress_year)
        .order('introduced_date DESC')
        .page(params[:page]).per(25)
    elsif params[:legislations][:issue_name]
      issue = Issue.find_by_name(params[:legislations][:issue_name])
      li = LegislationIssue.where(:issue_id => issue.id).includes(:legislation)
      @legislation = []
      li.each do |l|
        @legislation << l.legislation
      end
      @legislation = Kaminari.paginate_array(@legislation).page(params[:page]).per(25)
    elsif params[:legislations][:bill_number]
      bill = params[:legislations][:bill_number]
      bill_number = bill.gsub(/[^0-9]/, "")

      @legislation = Legislation.where(:bill_number => bill_number)
        .order('introduced_date DESC')
        .page(params[:page]).per(25)
    end

    respond_to do |format|
      format.js
    end
  end

  def search
    if params[:legislations][:introduced_year]
      year = params[:legislations][:introduced_year]
      @legislation = Legislation.where("introduced_year = ?", "#{year}").page(params[:page]).per(25)
    elsif params[:legislations][:session]
      congress_year = params[:legislations][:session]
      @legislation = Legislation.where(:session => congress_year).page(params[:page]).per(25)
    elsif params[:legislations][:issue_name]
      issue = Issue.find_by_name(params[:legislations][:issue_name])
      li = LegislationIssue.where(:issue_id => issue.id).includes(:legislation)
      @legislation = []
      li.each do |l|
        @legislation << l.legislation
      end
      @legislation = Kaminari.paginate_array(@legislation).page(params[:page]).per(25)
    end
  end

  def show
    if params[:bill_number]
      @legislation = Legislation.find_by_bill_number(params[:bill_number]).includes(:legislation_issues)
      @votes = get_votes
    else
      @legislation = Legislation.find(params[:id])
      @votes = get_votes
    end 
  end

  def list
    @legislation = Legislation.order('introduced_date DESC').page(params[:page]).per(25)
  end

  def new
    @legislation = Legislation.new
  end

  def edit
    @legislation = Legislation.find(params[:id])
  end

  def update
    @legislation = Legislation.find(params[:id])

    respond_to do |format|
      if @legislation.update_attributes(params[:legislation])
        format.html { 
          flash[:notice] = 'Legislation has been successfully updated.'
          render 'edit'  }
          format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @legislation.errors, status: :unprocessable_entity }
      end
    end
  end


  private

  def get_votes
    client = Congress::Client.new
    @votes = client.votes(:bill_id => @legislation.rtc_id)
  end
end

app/helpers/legislation_helper.rb
module LegislationHelper
  def remove_hyphens(string)
    string.gsub(/-/, "").gsub(/!/, "").gsub(/'/, "")
  end

  def parse_summary(summary)
    # TODO: summary_sp1 and summary_sp2 basically do nothing, we need to
    # look ahead and make sure that the NEXT NON DIGIT CHARACTER is
    # not a ")" or "}"
    summary_sp1 = summary.gsub(/(\.  ?=*\))/, '.<br>')
    summary_sp2 = summary_sp1.gsub(/(\. ?=*\))/, '.<br>').gsub(/\.<br>/, ".)")
    summary_sp3 = summary_sp2.split(': ').join(': <br>')
    summary_sp4 = summary_sp3.split(/\((?=\d)/).join('<br>(')
    summary_sp5 = summary_sp4.gsub(/<br><br>/, '<br>')

    summary = summary_sp5.html_safe
  end

  def split_voter_ids
    voter_ids = @votes['votes'].last['voter_ids']
    yeas = []
    nays = []
    abstains = []

    # split up into yeas, nays, abstains
    voter_ids.each do |id|
      if id[1] == 'Yea'
        yeas << id[0]
      elsif id[1] == 'Nay'
        nays << id[0]
      elsif id[1] == 'Not Voting'
        abstains << id[0]
      end
    end

    # compose sql statements
    find_yeas = "SELECT * FROM people WHERE "
    find_nays = "SELECT * FROM people WHERE "
    find_abstains = "SELECT * FROM people WHERE "

    yeas_length = yeas.length
    nays_length = nays.length
    abstains_length = abstains.length

    if yeas_length == 0
      @yeas = []
    else
      i = 0
      yeas.each do |y|
        if i == yeas_length - 1
          find_yeas = find_yeas + 
            "bioguide_id = '#{y.capitalize}'"
        else
          find_yeas = find_yeas + 
            "bioguide_id = '#{y.capitalize}' OR "
          i = i + 1
        end
      end
      @yeas = Person.find_by_sql(find_yeas)
    end

    if nays_length == 0
      @nays = []
    else
      i = 0
      nays.each do |n|
        if i == nays_length - 1
          find_nays = find_nays + 
            "bioguide_id = '#{n.capitalize}'"
        else
          find_nays = find_nays + 
            "bioguide_id = '#{n.capitalize}' OR "
          i = i + 1
        end
      end
      @nays = Person.find_by_sql(find_nays)
    end

    if abstains_length == 0
      @abstains = []
    else
      i = 0
      abstains.each do |a|
        if i == abstains_length - 1
          find_abstains = find_abstains + "bioguide_id = '#{a.capitalize}'"
        else
          find_abstains = find_abstains + 
            "bioguide_id = '#{a.capitalize}' OR "
          i = i + 1
        end
      end
      @abstains = Person.find_by_sql(find_abstains)
    end

    return @yeas, @nays, @abstains
  end

end

app/views/legislation/_legislation_pagination_partial.html.erb
<%= paginate @legislation, :window => 7 %>

app/views/legislation/_legislation_pagination_partial_refresh.html.erb
<%= paginate @legislation, :window => 7, :params => {:controller => 'legislation', :action => 'refresh'}, :remote => true %>

app/views/legislation/_legislation_partial.html.erb
<%= stylesheet_link_tag "legislation" %>
<div id="legislation-loader" style="display: none">
  <%= image_tag 'ajax-loader.gif' %>
</div>
<% if @legislation.count == 0 %>
<h2>No records found.</h2>
<% else %>
<table id="legislation-table">
  <thead>
    <tr>
      <th>Date</th>
      <th>Bill No.</th>
      <th>Bill Title</th>
      <th>Outcome</th>
      <% if can? :edit, Legislation %>
      <th>Edit</th>
      <% end %>
    </tr>
  </thead>
  <tbody>
    <% @legislation.each do |legislation| %>
    <tr class="<%= cycle("even", "odd") %>">
      <% if legislation.introduced_date.nil? %>
      <td></td>
      <% else %>
      <td><%= link_to legislation.introduced_date.to_date.strftime("%-m-%e\n%Y"), legislation %></td>
      <% end %>
      <td class="span3"><%= link_to "#{legislation.bill_type.upcase} #{legislation.bill_number}", legislation %></td>
      <td><%= link_to truncate(legislation.bill_title, :length => 110), legislation %></td>
      <% if legislation.passage_votes.empty? %>
      <td><%= legislation.latest_major_action %></td>
      <% else %>
      <% passage_votes = legislation.passage_votes %>
      <% last_vote = passage_votes.last %>
      <td><%= "#{last_vote.result.capitalize}ed #{last_vote.chamber.capitalize}"%></td>
      <% end %>
      <% if can? :edit, Legislation %>
      <td><%= link_to "Edit", edit_legislation_path(legislation) %></td>
      <% end %>
    </tr>
    <% end %>
  </tbody>
</table>
<% end %>

app/views/legislation/_legislation_search.html.erb
<div class="three columns" style="margin: 0;">
  <%= form_for :legislations, :remote => true, :url => {:action => 'refresh'} do |f| %>
  <label class="two columns">
    By Year
    <%= f.select :introduced_year, Legislation::YEARS, {}, :class => 'box_g', :style => 'width: 90px; height: 30px;' %>
  </label>
  <%= f.submit "Go", :class => 'no-padding box_red', :onclick => "$('#legislation-table').hide();$('#legislation-loader').show();" %>
  <% end %>
</div>
<div class="three columns" style="margin: 0;">
  <%= form_for :legislations, :remote => true, :url => {:action => 'refresh'} do |f| %>
  <label class="two columns">
    By Bill Number
    <%= f.text_field :bill_number, :class => 'box_g', :style => 'width: 90px; height: 20px;' %>
  </label>
  <%= f.submit "Go", :class => 'no-padding box_red', :onclick => "$('#legislation-table').hide();$('#legislation-loader').show();" %>
  <% end %>
</div>
<div class="three columns" style="margin: 0;">
  <%= form_for :legislations, :remote => true, :url => {:action => 'refresh'} do |f| %>
  <label class="two columns">
    By Session
    <%= f.select :session, Legislation::SESSIONS, {}, :class => 'box_g', :style => "height: 30px; width: 100px;" %>
  </label>
    <%= f.submit "Go", :class => 'no-padding box_red', :onclick => "$('#legislation-table').hide();$('#legislation-loader').show();" %>
  <% end %>
</div>
<div class="four columns" style="margin: 0;">
  <%= form_for :legislations, :remote => true, :url => {:action => 'refresh'} do |f| %>
  <label class="three columns" style="width: 140px">
    By Issue
    <%= f.text_field :issue_name, :class => 'issues-list box_g', :data => {issues_source: api_autocomplete_autocomplete_issues_name_path}, :style => 'width: 130px;' %>
  </label>
  <%= f.submit "Go", :class => 'no-padding box_red', :onclick => "$('#legislation-table').hide();$('#legislation-loader').show();" %>
  <% end %>
</div>

app/views/legislation/_legislation_search_noremote.html.erb
<div class="three columns">
  <%= form_for :legislations, :url => {:action => 'search'} do |f| %>
  <label class="two columns">
    By Year
    <%= f.select :introduced_year, Legislation::YEARS, {}, :class => 'box_g', :style => 'width: 90px; height: 30px;' %>
  </label>
  <%= f.submit "Go", :class => 'no-padding box_red', :onclick => "$('#legislation-table').hide();$('#legislation-loader').show();" %>
  <% end %>
</div>
<div class="four columns">
  <%= form_for :legislations, :url => {:action => 'search'} do |f| %>
  <label class="three columns">
    By Session
    <%= f.select :session, Legislation::SESSIONS, {}, :class => 'box_g', :style => "height: 30px;" %>
  </label>
  <%= f.submit "Go", :class => 'no-padding box_red', :onclick => "$('#legislation-table').hide();$('#legislation-loader').show();" %>
  <% end %>
</div>
<div class="four columns">
  <%= form_for :legislations, :url => {:action => 'search'} do |f| %>
  <label class="three columns">
    By Issue
    <%= f.text_field :issue_name, :class => 'issues-list box_g', :data => {issues_source: api_autocomplete_autocomplete_issues_name_path}, :style => 'width: 150px;' %>
  </label>
  <%= f.submit "Go", :class => 'no-padding box_red', :onclick => "$('#legislation-table').hide();$('#legislation-loader').show();"%>
  <% end %>
</div>

app/views/legislation/_noremote_new.html.erb
<div class="three columns">
  <%= form_for :legislations, :url => {:action => 'search'} do |f| %>
  <label class="two columns">
    By Year
    <%= f.select :introduced_year, Legislation::YEARS, {}, :class => 'box_g', :style => 'width: 90px; height: 30px;' %>
  </label>
  <%= f.submit "Go", :class => 'no-padding box_red', :onclick => "$('#legislation-table').hide();$('#legislation-loader').show();" %>
  <% end %>
</div>
<div class="four columns">
  <%= form_for :legislations, :url => {:action => 'search'} do |f| %>
  <label class="three columns">
    By Session
    <%= f.select :session, Legislation::SESSIONS, {}, :class => 'box_g', :style => "height: 30px;" %>
  </label>
  <%= f.submit "Go", :class => 'no-padding box_red', :onclick => "$('#legislation-table').hide();$('#legislation-loader').show();" %>
  <% end %>
</div>
<div class="four columns">
  <%= form_for :legislations, :url => {:action => 'search'} do |f| %>
  <label class="three columns">
    By Issue
    <%= f.text_field :issue_name, :class => 'issues-list box_g', :data => {issues_source: api_autocomplete_autocomplete_issues_name_path}, :style => 'width: 150px;' %>
  </label>
  <%= f.submit "Go", :class => 'no-padding box_red', :onclick => "$('#legislation-table').hide();$('#legislation-loader').show();"%>
  <% end %>
</div>

app/views/legislation/edit.html.erb
<style type="text/css">
  input, textarea, select, .uneditable-input {
    border: 1px solid #CCCCCC;
    border-radius: 3px 3px 3px 3px;
    color: gray;
    display: inline-block;
    font-size: 13px;
    line-height: 18px;
    padding: 4px;
    width: 500px;
  }
</style>

<div class="content-wrap">
  <%= form_for(@legislation, :html => { :class => 'form-stacked' }) do |f| %>
  <h1>Editing <%= @legislation.bill_type.upcase %> <%= @legislation.bill_number %></h1>
    <%= error_messages_for(@legislation) %>

    <%= f.label :summary %>
    <%= f.text_area :summary, :rows => 10 %>

    <p>
      <b>Title:</b>
      <%= @legislation.bill_title %>
    </p>

    <p>
      <b>Sponsor:</b>
      <a href="<%= person_path(Person.find_by_bioguide_id(@legislation.bill_sponsor_id)) %>"><%= @legislation.bill_sponsor %></a>
    </p>

    <p>
      <b>Introduced:</b>
      <%= @legislation.introduced_date %> (Congress Year: <%= @legislation.congress_year %>)
    </p>

    <p>
      <b>Last Major Action:</b>
      <%= @legislation.latest_major_action_date %> - <%= @legislation.latest_major_action %>
    </p>

    <p>
      <b>Cosponsors:</b>
      <%= @legislation.legislation_cosponsors.collect { |c| 
        "<a href='#{person_path(Person.find_by_id(c.person_id))}'>#{Person.find_by_id(c.person_id).first_name} #{Person.find_by_id(c.person_id).last_name}</a>"
      }.to_sentence.html_safe %>
    </p>

    <p>
      <b>Legislation Issues:</b>
      <%= @legislation.issues.collect { |i| "<a href='/issues/#{Issue.where("name like ?", "%#{i.name}").first.id}'>#{i.name}</a>" }.to_sentence.html_safe %>
    </p>		

    <p>
      <b>Committees:</b>
      <%= @legislation.committees.collect { |c| "<a href='/committees/#{Committee.where("name like ?", "%#{c.name}").first.id }'>#{c.name}</a>" }.to_sentence.html_safe %>
    </p>

    <%= f.submit :class => 'button' %>

  <% end %>
</div>

app/views/legislation/grab_xml.html.erb
<h1><%= @title %></h1>

<p>
	<b>Date:</b>
	<%= @date %>
</p>
<p>
	<b>Congress:</b>
	<%= @congress %>
</p>
<p>
	<b>Session:</b>
	<%= @session %>
</p>
<p>
	<b>Legislation Number:</b>
	<%= @legis_num %>
</p>
<p>
	<b>Sponsor:</b>
		<%= @sponsor %>
</p>
<p>
	<b>Cosponsors:</b>
		<%= @cosponsors %>
</p>
<p>
	<b>Committee Name:</b>
		<% @committee_names.each do |committee| %>
			<%= committee['committee-name'] %>
		<% end %>
</p>

<p>
	<b>Body:</b>
	<%= @body %>
</p>
<p>
	<b></b>
	
</p>

app/views/legislation/index.html.erb
<div class="sixteen columns">
  <div class="four columns">
    <h1 class="page-title">Legislation</h1>
  </div>
  <%= render :partial => 'legislation_search' %>
</div>

<div id="legislation-container" class="fifteen columns box_a" style="margin-left: 20px;">
  <div id="legislation">
    <%= render :partial => 'legislation_partial', :locals => { :legislation => @legislation } %>
  </div>
  <div id="paginator">
    <%= render :partial => 'legislation_pagination_partial', :locals => { :legislation => @legislation } %>
  </div>
</div>

app/views/legislation/list.html.erb
<div class="sixteen columns">
  <div class="four columns">
    <h1 class="page-title">Legislation</h1>
  </div>
  <div class="three columns">
    <%= form_for :legislations, :remote => true, :url => {:action => 'refresh'} do |f| %>
    <label class="two columns">
      By Year
      <%= f.text_field :introduced_year, :class => 'box_g', :style => 'width: 90px;' %>
    </label>
    <%= f.submit "Go", :class => 'no-padding box_red' %>
    <% end %>
  </div>
  <div class="four columns">
    <%= form_for :legislations, :remote => true, :url => {:action => 'refresh'} do |f| %>
    <label class="three columns">
      By Session
      <%= f.select :session, Legislation::SESSIONS, {}, :class => 'box_g', :style => "height: 30px;" %>
    </label>
    <%= f.submit "Go", :class => 'no-padding box_red' %>
    <% end %>
  </div>
  <div class="four columns">
    <%= form_for :legislations, :remote => true, :url => {:action => 'refresh'} do |f| %>
    <label class="three columns">
      By Issue
      <%= f.text_field :issue_name, :class => 'issues-list box_g', :data => {issues_source: api_autocomplete_autocomplete_issues_name_path}, :style => 'width: 150px;' %>
    </label>
    <%= f.submit "Go", :class => 'no-padding box_red' %>
    <% end %>
  </div>
</div>

<div id="legislation-container" class="fifteen columns box_a" style="margin-left: 20px;">
  <div id="legislation">
    <%= render :partial => 'legislation_partial', :locals => { :legislation => @legislation } %>
  </div>
  <div id="paginator">
    <%= render :partial => 'legislation_pagination_partial', :locals => { :legislation => @legislation } %>
  </div>
</div>

app/views/legislation/make_list.html.erb
<h1>List of Bills for 112th Year of Congress</h1>

<% @bills.each do |bill| %>
	<%= bill %><br />
<% end %>

app/views/legislation/refresh.js.erb
$('#legislation-container').html("<%= escape_javascript(render(:partial => 'legislation_partial', :locals => {:legislation => @legislation})).html_safe %><div id='paginator'><%= escape_javascript(render(:partial => 'legislation_pagination_partial_refresh', :locals => {:legislation => @legislation})).html_safe %></div>")
$('#legislation-table').show()

app/views/legislation/search.html.erb
<div class="sixteen columns">
  <div class="four columns">
    <h1 class="page-title">Legislation</h1>
  </div>
  <%= render :partial => 'legislation_search' %>
</div>

<div id="legislation-container" class="fifteen columns box_a" style="margin-left: 20px;">
  <div id="legislation">
    <%= render :partial => 'legislation_partial', :locals => { :legislation => @legislation } %>
  </div>
  <div id="paginator">
    <%= render :partial => 'legislation_pagination_partial', :locals => { :legislation => @legislation } %>
  </div>
</div>

app/views/legislation/show.html.erb
<div class="content-wrap">
  <div class="sixteen columns">
    <div class="four columns omega">
      <h1 class="page-title">Legislation</h1>
    </div>
    <%= render :partial => 'legislation_search_noremote' %>
  </div>

  <article>
  <div class="twelve columns">
    <h1 id="session-number"><%= @legislation.session.ordinalize %> Congress</h1>
    <h2 id="bill-number">
      <%= @legislation.bill_type.upcase %> <%= @legislation.bill_number %>
    </h2>
    
    <h4 id="legislation-title" style="font-size: 14px;"><%= @legislation.bill_title %></h4>
    <div class="bill_pdf box_b" style="margin-left: 9px;">
      <% if @legislation.summary %>
        <h5 id="summary-title">Summary</h5>
        <p style="font-size: 12px;"><%= parse_summary(@legislation.summary) %></p>
      <% else %>
        <p style="font-size: 12px;">No summary for this bill</p>
      <% end %>
    </div>
  </div>

  <div class="four columns">
    <div id="full_text" class="box_d">
      <% if @legislation.bill_pdf %>
        <h2><a href="<%= @legislation.bill_pdf %>" style="color: #FFF; text-decoration: none;">Download PDF</a></h2>
      <% else %>
        <h2>No PDF</h2>
      <% end %>
    </div>

    <aside id="status" class="box_c">
      <h2>Status</h2>
      <% if @legislation.actions %>
      <% actions = @legislation.actions.order('acted_at ASC').take(4) %>
      <table>
        <% actions.each do |a| %>
        <tr>
          <td><%= truncate(a.text, :length => 80) %></td>
          <td><%= a.acted_at.to_date %></td>
        </tr>
        <% end %>
        <% if @legislation.passage_votes %>
        <% passage_votes = @legislation.passage_votes %>
        <% passage_votes.each do |pv| %>
        <tr>
          <td><%= "#{pv.result}ed".capitalize %> <%= pv.chamber.capitalize %></td>
          <td><%= pv.voted_at.to_date %></td>
        </tr>
        <% end %>
        <% end %>
      </table>
      <% else %>
        No actions recorded.
      <% end %>
    </aside>

    <aside id="votes" class="box_d">
      <% if @votes['count'] == 0 %>
        <h2>No Votes</h2>
      <% else %>
        <% vote = @votes['votes'].last %>
        <% breakdown = vote.vote_breakdown.total %>
        <% yea = breakdown.yea %>
        <% nay = breakdown.nay %>
        <h2 id="votes-header">
          <a href="#" onclick="return false;" style="color: #fff;"> 
            Votes: Yea (<%= yea %>) - Nay (<%= nay %>)
          </a>
        </h2>
        <div id="voter-ids" class="box_a" style="display: none;">
          <p class="close-button">Close X</p>
          <h5>Votes</h5>
          <% split_voter_ids %>
          <div id="yea">
            <p>Yea (<%= @yeas.count %>)</p>
            <ul id="yea-list">
              <% @yeas.each do |y| %>
              <li>
                <%= link_to "[#{y.state_represented}-#{y.district}] #{y.full_name} (#{y.current_party})", person_path(y.id) %>
              </li>
              <% end %>
            </ul>
          </div>
          <div id="nay">
            <p>Nay (<%= @nays.length %>)</p>
            <ul id="nay-list">
              <% @nays.each do |n| %>
              <li>
                <%= link_to "[#{n.state_represented}-#{n.district}] #{n.full_name} (#{n.current_party})", person_path(n.id) %>
              </li>
              <% end %>
            </ul>
          </div>
          <div id="abstain">
            <p>Abstain (<%= @abstains.count %>)</p>
            <ul id="abstain-list">
              <% @abstains.each do |a| %>
              <li>
                <%= link_to "[#{a.state_represented}-#{a.district}] #{a.full_name} (#{a.current_party})", person_path(a.id) %>
              </li>
              <% end %>
            </ul>
          </div>
        </div>
      <% end %>
    </aside>

    <aside id="issues" class="box_c">
      <h2>Issues (sectors)</h2>
      <% legislation_issues = @legislation.legislation_issues.includes(:issue) %>
      <% issue_count = legislation_issues.count %>
      <% n = 1 %>
      <% legislation_issues.each do |i| %>
      <% issue = i.issue %>
      <% if n < 7 %>
        <p><a href="/issues/<%= issue.to_param %>"><%= issue.name %></a></p>
      <% elsif n == 7 %>
        <p>
          <%= link_to "more...", "#", :id => "more-issues", :onclick => "return false;" %>
        </p>
        <p class="hidden-issue" style="display:none;">
          <%= link_to issue.name, issue_path(issue.to_param) %>
        </p>
      <% else %>
        <p class="hidden-issue" style="display:none;">
          <%= link_to issue.name, issue_path(issue.to_param) %>
        </p>
      <% end %>
        <% n = n + 1 %>
      <% end %>
    </aside>

    <aside id="sponsors" class="box_c">
      <h2>Sponsor</h2>
        <% unless Person.find_by_bioguide_id(@legislation.bill_sponsor_id).nil? %>
          <p><a href="<%= person_path(Person.find_by_bioguide_id(@legislation.bill_sponsor_id)) %>"><%= @legislation.bill_sponsor %></a></p>
        <% end %>
    </aside>

    <aside id="cosponsors" class="box_d">
      <% cosponsors = @legislation.legislation_cosponsors.includes(:person) %>
      <h2 id="cosponsors-header"><a href="#" onclick="return false;">Cosponsors (<%= cosponsors.count %>)</a> <span class="plus-button">+</span></h2>
      <ul id="cosponsors-list">
        <% cosponsors.each do |c| %>
          <p><%= link_to c.person.name, person_path(c.person.id) %></p>
        <% end %>
      </ul>
    </aside>

    <aside id="committees" class="box_c">
      <h2>Committees</h2>
      <% committees = CommitteeLegislation.where(:legislation_id => @legislation.id).includes(:committee) %>
      <% committees.each do |c| %>
        <% com = Committee.find(c.committee_id) %>
        <p><%= link_to com.name, com %></p>
      <% end %>
    </aside>

    <aside id="prognosis" class="box_c">
      <h2>SOURCE</h2>
      <p><%= link_to "Congressional Research Service", 'http://www.loc.gov/crsinfo/' %></p>
    </aside>

  </div>
  </article>
</div>