config/routes.rb
Politics411::Application.routes.draw do  

  get "subcommittees/index"
  get "subcommittees/show"

  get "legislation/search"
  get "legislation/refresh"

  match "subcommittees/:id" => "subcommittees#show"

  get "contributor/show"

  get "committees/index"
  get "committees/manage"

  match "senators" => "people#senators"
  match "representatives" => "people#representatives"

  get "people/senators"
  get "people/representatives"
  get "people/refresh_officials"
  get "people/switch_to_representative_by_state"
  get "people/switch_to_representative_by_name"
  get "people/switch_to_representative_by_party"
  get "people/switch_to_senator_by_state"
  get "people/switch_to_senator_by_party"
  get "people/switch_to_senator_by_name"
  get "people/refresh_bubble_rect"
  get "people/person_not_found"
  post "people/search"

  get "api/autocomplete/autocomplete_person_name"
  get "api/autocomplete/autocomplete_person_name_to_slug"
  get "api/autocomplete/autocomplete_person_url"
  get "api/autocomplete/autocomplete_religion_name"
  get "api/autocomplete/autocomplete_university_name"
  get "api/autocomplete/autocomplete_organization_name"
  get "api/autocomplete/autocomplete_main_issues_name"
  get "api/autocomplete/autocomplete_issues_name"

  get "api/people/index"

  get "login" => "sessions#new", :as => "login"
  get "logout" => "sessions#destroy", :as => "logout"
  get "signup" => "users#new", :as => "signup"

  resources :people do
    member do 
      get 'videos'
      get 'articles'
    end
  end
  resources :main_issues
  resources :issues
  resources :committees
  resources :subcommittees
  resources :legislation
  resources :users
  resources :password_resets
  resources :sessions
  resources :contributors_interest_group_sectors
  resources :contributors_interest_groups
  resources :contributors_pacs
  resources :political_offices
  resources :earmarks
  resources :sponsored_legislations  
  resources :campaign_platforms
  resources :supporters
  resources :contributors
  resources :articles 
  resources :attachments
  resources :personal_assets
  resources :transactions
  resources :litigations
  resources :accusations
  resources :endorsements
  resources :professional_experiences
  resources :business_associates
  resources :organizations
  resources :flip_flops
  resources :videos
  resources :family_members
  resources :religions
  resources :universities 
  resources :degrees

  root :to => "people#representatives"

  match ':controller(/:action(/:id(.:format)))'
end

app/views/layouts/_admin-scripts.html.erb
<%= stylesheet_link_tag 'twitter/bootstrap' %>
<%= stylesheet_link_tag 'jquery.wysiwyg.css' %>
<%= javascript_include_tag 'jquery.wysiwyg.js' %>
<%= javascript_include_tag 'controls/wysiwyg.image.js' %>
<%= javascript_include_tag 'controls/wysiwyg.link.js' %>
<%= javascript_include_tag 'controls/wysiwyg.table.js' %>
<script type="text/javascript">
  (function($) {
    $(document).ready(function() {
      $('.wysiwyg').wysiwyg({
        initialContent: "",
        iFrameClass: "full-width",
        controls: {
          strikeThrough: {visible: false},
          subscript: {visible: false},
          superscript: {visible: false},
          indent: {visible: false},
          outdent: {visible: false},
          h1: {visible: false},
          h2: {visible: false},
          h3: {visible: false},
          justifyLeft: {visible: false},
          justifyRight: {visible: false},
          justifyCenter: {visible: false},
          justifyFull: {visible: false},
          removeFormat: {visible: false},
          insertImage: {visible: false},
          code: {visible: false},
          undo: {visible: false},
          redo: {visible: false}
        }
      });
    });
  })(jQuery);
</script>

app/views/layouts/_messages.html.erb
<div id="notice">
	<% if flash[:error] %>
		<p>
			<%= flash[:error] %>
			<a class="close" data-dismiss="alert" href="#">&times;</a>
		</p>
	<% end %>
	<% if notice %>	
		<p>
			<%= notice %>
			<a class="close" data-dismiss="alert" href="#">&times;</a>
		</p>
	<% end %>
</div>

app/views/layouts/_supporters_pie.html.erb
<script type="text/javascript">
window.onload = function () {
    var r = Raphael("holder", 320, 240),
        pie = r.piechart(100, 140, 75, <%= @person.supporter_numbers %>, { legend: ['%%.%%'], legendpos: "east"});

    r.text(100, 40, "Supporters (By Race)").attr({ font: "20px sans-serif" });
    pie.hover(function () {
        this.sector.stop();
        this.sector.scale(1.1, 1.1, this.cx, this.cy);

        if (this.label) {
            this.label[0].stop();
            this.label[0].attr({ r: 7.5 });
            this.label[1].attr({ "font-weight": 800 });
        }
    }, function () {
        this.sector.animate({ transform: 's1 1 ' + this.cx + ' ' + this.cy }, 500, "bounce");

        if (this.label) {
            this.label[0].animate({ r: 5 }, 500, "bounce");
            this.label[1].attr({ "font-weight": 400 });
        }
    });
};
</script>

app/views/layouts/_topbar.html.erb
<div class="container">
  <div class="topbar-wrapper">
    <div class="topbar">
      <div class="topbar-inner">
        <div class="container">
          <a class="brand" href="/" style="padding:0 10px;"><%= image_tag 'glasspen.png' %></a>
          <ul class="nav" data-dropdown="dropdown">
            <li class="dropdown">
              <a href="/" class="dropdown-toggle">View</a>
              <ul class="dropdown-menu">
                <li><%= link_to "View Senators", people_senators_path %></li>
                <li><%= link_to "View Representatives", people_representatives_path %></li>
                <li><%= link_to "View Committees", committees_index_path %></li>
                <li><%= link_to "View Subcommittees", subcommittees_index_path %></li>
              </ul>
            </li>
            <% if can? :edit, Person %>
            <li class="dropdown">
              <a href="/" class="dropdown-toggle">Add</a>
              <ul class="dropdown-menu">
                <li><%= link_to('Add Organization', { :controller => 'organizations', :action => 'new' }) %></li>
                <li><%= link_to('Add University', { :controller => 'universities', :action => 'new' }) %></li>
                <li><%= link_to('Add Religion', { :controller => 'religions', :action => 'new' }) %></li>
                <li class="divider"></li>
                <li><%= link_to 'Create New Person', new_person_path %></li>
              </ul>
            </li><% end %><% if can? :edit, Person %>
            <li class="dropdown">
              <a href="/" class="dropdown-toggle">Manage</a>
              <ul class="dropdown-menu">
                <li><%= link_to('People', { :controller => 'people', :action => 'index' }) %></li>
                <li><%= link_to('Issues', { :controller => 'issues', :action => 'index' }) %></li>
                <li><%= link_to('Committees', { :controller => 'committees', :action => 'manage' }) %></li>
                <li><%= link_to('Organizations', { :controller => 'organizations', :action => 'index' }) %></li>
                <li><%= link_to('Universities', { :controller => 'universities', :action => 'index' }) %></li>
                <li><%= link_to('Religions', { :controller => 'religions', :action => 'index' }) %></li>
              </ul>
            </li><% end %><% if can? :manage, :all %>
            <li class="dropdown">
              <a href="/" class="dropdown-toggle">Users</a>
              <ul class="dropdown-menu">
                <li>
                  <%= link_to "Manage Users", users_path %>
                </li>
                <li>
                  <%= link_to "Create New User", signup_path %>
                </li>
              </ul>
            </li><% end %>
          </ul>
          <p class="user-nav pull-right" style="color: #fff;">
            <% if current_user %> 
            Logged in as <%= current_user.username %> <%= link_to "log out", logout_path %> 
            <% else %> 
            <%= link_to "log in", login_path %> 
            <% end %>
          </p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>American Politics 411 | <%= @page_title %></title>
  <%= stylesheet_link_tag    "application" %>
	<%= stylesheet_link_tag    "public" %>
  <%= javascript_include_tag "application" %>
	<%= javascript_include_tag "person" %>
  <%= csrf_meta_tags %>

</head>
<body>
	<!-- TOPBAR  -->
	<%= render 'layouts/topbar' %>

	
	<!-- BODY -->
	<%= yield %>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Politics411</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/public.html.erb
<!doctype html>
<html lang="en">
  <head>
    <title>American Politics 411 | <%= @page_title %></title>
    <%= stylesheet_link_tag    'base', 'skeleton', 'layout', 'style', 'person', 'committees', 'application', 'public' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>

    <!--[if lt IE 9]>
    <script src="iefixes/html5shiv.js"></script>
    <script src="iefixes/selectivizr-min.js"></script>
    <script>
      $(document).ready(function() {
        $('#header-nav ul li').css({"float": "left"});
        $('#menu-item-news').css({"width": "80px", "padding-left": "60px"});
      });
    </script>
    <![endif]-->

    <script>
      (function() {
        var cx = '003827569551005567108:byo6hypvaji';
        var gcse = document.createElement('script'); gcse.type = 'text/javascript'; gcse.async = true;
        gcse.src = (document.location.protocol == 'https:' ? 'https:' : 'http:') +
        '//www.google.com/cse/cse.js?cx=' + cx;
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(gcse, s);
      })();
    </script>
    <script type='text/javascript'>
      (function (d, t) {
        var bh = d.createElement(t), s = d.getElementsByTagName(t)[0];
        bh.type = 'text/javascript';
        bh.src = '//www.bugherd.com/sidebarv2.js?apikey=cicnxxbktlq96gt8y3iwpq';
        s.parentNode.insertBefore(bh, s);
      })(document, 'script');
    </script>
    <script type="text/javascript">
      var _qevents = _qevents || [];
      (function() {
      var elem = document.createElement('script');
      elem.src = (document.location.protocol == "https:" ? "https://secure" : "http://edge") + ".quantserve.com/quant.js";
      elem.async = true;
      elem.type = "text/javascript";
      var scpt = document.getElementsByTagName('script')[0];
      scpt.parentNode.insertBefore(elem, scpt);
      })();
      _qevents.push({
      qacct:"p-zDSJvX5A5tzaF"
      });
    </script>
      <noscript>
      <div style="display:none;">
      <img src="//pixel.quantserve.com/pixel/p-zDSJvX5A5tzaF.gif" border="0" height="1" width="1" alt="Quantcast"/>
      </div>
      </noscript>
    <script type="text/javascript">
      var _gaq = _gaq || [];
      _gaq.push(['_setAccount', 'UA-35092756-1']);
      _gaq.push(['_trackPageview']);
      (function() {
        var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
      })();
    </script>
  </head>

  <body>
    <!-- topbar -->
    <% if current_user %>
    <%= render 'layouts/admin-scripts' %>
    <%= render 'layouts/topbar' %>
    <% end %>

    <!-- HEADER -->
    <header id="header" class="container">
      <div class="one-third column">
        &nbsp;
        <div id="social-media-buttons-header">
          <ul>
            <li>
              <a href="https://www.youtube.com/user/americanpoliticsinfo/featured" id="yt-link-top"></a>
            </li>
            <li>
              <a href="http://www.facebook.com/AP411" id="facebook-link-top"></a>
            </li>
            <li>
              <a href="https://twitter.com/AP_411" id="twitter-link-top"></a>
            </li>
            <li>
              <a href="http://www.americanpolitics411.com/article/feed" id="rss-link-top"></a>
            </li>
          </ul>
        </div>
        <div id="time-now"><%= Time.now.to_date.strftime("%e %B %Y") %></div>
      </div>
      <div class="one-third column logo">
        <a href="http://www.americanpolitics411.com" ><img src="/assets/beta.png"></a>
      </div>
      <div class="one-third column">
        <div class="google-search"><gcse:searchbox-only></gcse:searchbox-only></div>
      </div>
    </header>

    <!-- NAVIGATION -->
    <div id="content-wrap" class="container clearfix">
      <nav id="header-nav" class="sixteen columns clearfix">
        <ul id="menu-header" class="menu clearfix">
          <li id="menu-item-news"><a href="http://www.americanpolitics411.com/news/">News</a></li>
          <li id="menu-item-research" class="menu-item"><a href="http://www.americanpolitics411.com/research/">Research</a></li>
          <li id="menu-item-events" class="menu-item"><a href="http://www.americanpolitics411.com/event/">Events</a></li>
          <li id="menu-item-officials" class="menu-item"><a href="http://opensource.americanpolitics411.com/people/representatives">Officials</a></li>
          <li id="menu-item-legislation" class="menu-item"><a href="http://opensource.americanpolitics411.com/legislation">Legislation</a></li>
          <li id="menu-item-pundit-cafe" class="menu-item"><a href="http://www.americanpolitics411.com/pundit-cafe/">The Pundit Cafe</a></li>
          <li id="menu-item-internships" class="menu-item"><a href="http://www.americanpolitics411.com/internships/">Internships</a></li>
        </ul>
      </nav>
      <!-- BODY -->
      <%= yield %>

      <hr class="sixteen columns">
    </div>

    <!-- FOOTER -->
    <footer id="footer" class="container clearfix">
      <nav id="footer-nav" class="twelve columns alpha">
        <ul id="menu-footer" class="menu clearfix"><li class="menu-item"><a href="http://www.americanpolitics411.com/news/">News</a></li>
          <li class="menu-item"><a href="http://www.americanpolitics411.com/research/">Research</a></li>
          <li class="menu-item"><a href="http://www.americanpolitics411.com/event/">Events</a></li>
          <li class="menu-item"><a href="http://opensource.americanpolitics411.com/people/representatives">Officials</a></li>
          <li class="menu-item"><a href="http://opensource.americanpolitics411.com/legislation">Legislation</a></li>
          <li class="menu-item"><a href="http://www.americanpolitics411.com/pundit-cafe/">The Pundit Cafe</a></li>
          <li class="menu-item"><a href="http://www.americanpolitics411.com/internships/">Internships</a></li>
          <li class="menu-item"><a href="http://www.americanpolitics411.com/about-us/">About</a></li>
          <li class="menu-item"><a href="http://www.americanpolitics411.com/contact-us/">Contact</a></li>
        </ul>   
      </nav>

      <div class="four columns omega">
        <p class="copyright">Copyright 2012 American Politics 411</p>
      </div>
      <div class="four columns omega">
        &nbsp;
        <div id="social-media-buttons-footer">
          <ul>
            <li>
              <a href="https://www.youtube.com/user/americanpoliticsinfo/featured" id="yt-link-bottom"></a>
            </li>
            <li>
              <a href="http://www.facebook.com/AP411" id="facebook-link-bottom"></a>
            </li>
            <li>
              <a href="https://twitter.com/AP_411" id="twitter-link-bottom"></a>
            </li>
            <li>
              <a href="http://www.americanpolitics411.com/article/feed" id="rss-link-bottom"></a>
            </li>
          </ul>
        </div>
      </div>
    </footer>
  </body>
</html>